name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.1
        env:
          MYSQL_ROOT_PASSWORD: giasfelfebrehber
          MYSQL_DATABASE: usersdb
        ports:
          - 3306:3306
          options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3


    steps:

    - name: Configure Mysql permission
      run: mysql -h 127.0.0.1 --port 3306 -u root -pgiasfelfebrehber -e "ALTER USER 'root'@'%' IDENTIFIED BY 'giasfelfebrehber'; GRANT ALL PRIVILEGES ON *.* TO 'root'@'%'; FLUSH PRIVILEGES;"

    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '14'
    - name: Install dependencies
      run: npm install
    
    - name: Install client mysql
      run: sudo apt install mysql-client
    - name: Criar tabelas
      run: mysql -h 127.0.0.1 --port 3306 -u root -pgiasfelfebrehber usersdb < estrutura.sql
    - name: Run tests
      run: npm test
